apiVersion: v1
kind: Service
metadata:
  name: tms-backend
  labels:
    app: tms-backend
spec:
  type: NodePort
  selector:
    app: tms-backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
      name: http
