apiVersion: v1
kind: Service
metadata:
  name: tms-frontend
  labels:
    app: tms-frontend
spec:
  type: NodePort
  selector:
    app: tms-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
